name: AI Assistant Pipeline
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "ok: workflow detected"
